version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - 5432:5432
    volumes:
      - "./data:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
