version: "3.8"

services:
  node:
    container_name: API
    build: 
      context : ./api
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST: postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - 5432:5432
    volumes:
      - "./data:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
