version: "3"

services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: cashmanager
    expose:
      - 5432
    volumes:
      - "./data:/var/lib/postgresql/data"

  node:
    container_name: API
    build:
      context: ./api
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST: postgres
      VIRTUAL_HOST: api-bank.moriceau.dev
      DATABASE_URL: postgresql://${PGUSER}:${PGPASSWORD}@postgres:5432/product?schema=public
      APP_PORT: 3000
    depends_on:
      - postgres

  product:
    container_name: API_Product
    build:
      context: ./product_api
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST: postgres
      VIRTUAL_HOST: api-product.moriceau.dev
      DATABASE_URL: postgresql://${PGUSER}:${PGPASSWORD}@postgres:5432/product?schema=public
      APP_PORT: 3001
    depends_on:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: nginx-proxy
