version: "3"

services:
  postgres-db:
    container_name: postgres-time-manager
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - 5432:5432
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - postgres-network

volumes:
  db-data: {}

networks:
  postgres-network:
    name: postgres-network
