@startuml Architecture

package "Serveur Bank" {
    node Bank_server
    database Database_bank
    Bank_server - Database_bank   
}

package "Serveur Produit"{
    node Product_server
    database Database_client
    Database_client - Product_server
}


[TPE]
[Application]

Bank_server -- TPE : API
TPE - [Application]: Serial
Product_server -- [Application] : API


@enduml
