@startuml Class

hide methods

class User {
    - id: number
    - firstName: string
    - lastName: string
    - username: string
    - account_id: uuid
    - is_admin: boolean
}

class Account {
    - id: number
    - credit_card_rfif: string
    - cheque_uuid: string
    - balance: number
    - refusal_count: number
    - ceiling: number
    - max_overdraft: number
    - created_at: date
    - blocked: boolean
}

class Transaction {
    - id: number
    - amount: number
    - date: date
    - account_from: number
    - account_to: number
    - cancel: boolean
    - type: string
    - TPE_id: number
}

User "1" -- "0..1" Account : has
Account "1" - "0..*" Transaction : account_from

Account "1" - "0..*" Transaction : account_to

@enduml
