@startuml
class user{
    -id: int
    -name: String
    -firstName: String
    -password: String
    -admin: Bool
}

class Account{
    -id: int
    -money: int
    -refus: int
    -plafond: int
    -max_decouver: int
    -date_creation: Date
    -status: Status
    -RFIDUUID: int
    -chetUUID: int
}

class Produits{
    -uudi: int
    -reference: String
    -name: String
}


enum Status{
    ACTIVE
    CLOSED
    FROZEN
}

user "1" -- "0..*" Account



@enduml