on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/TPE/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # this cache the platformio binaries and not the .pio folder
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/TPE/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install PlatformIO
        run: pip install platformio

      - name: Go to TPE
        run: cd TPE

      - name: Build the project
        run: platformio run

      - name: Test the project
        run: platformio check --fail-on-defect high
